language:       cpp
compiler:       g++
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - >
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y mesa-common-dev libasound2-dev libfreetype6-dev
                            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
                            freeglut3-dev libxcomposite-dev libjack-dev
                            libcurl4-gnutls-dev g++-4.8 gcc-4.8
script:
  - make CONFIG=Release
after_success:
